### ISSUE TITLE
Feature Request: Change the title of the Remove button to Delete

### ISSUE THREAD

**Issue by everetteallen** [BIG-RAT/Prune#10]
It is confusing to have a button titled remove that actually deletes the object and instructions that say to Option-Click to remove an item from the list without deleting it from the server.  Would be great if the title of the Remove button could be changed to Delete to avoid confusion and reflect it's actual function.  Thanks!

**Comment by BIG-RAT** [comment]
I like it.  Think delete might also carry more weight and have folks double check before ~~removing~~ deleting things by mistake.  Change done.
