### ISSUE TITLE
Restricted Software Record exclusions are considered unscoped

### ISSUE THREAD

**Issue by jdemaio** [BIG-RAT/Prune#12]
I had one group named "Eligible for Monterey" that showed up as unscoped but is currently scoped as an exclusion for restricted software record. I do not use the group anywhere else.

Not sure if this is intended or not possible but thought it was worth mentioning.

**Comment by BIG-RAT** [comment]
Not intended but expected as restricted software wasn't being checked - should be good in v2.0.0.  Thanks for the heads up.
