### ISSUE TITLE
Prune not deleting scripts from Jamf version 10.35...

### ISSUE THREAD

**Issue by everetteallen** [BIG-RAT/Prune#14]
I have been trying to use Prune 2.0 to remove scripts from cloud hosted Jamf Pro 10.35.0 with no luck.  Using a list of 2 scripts app just sits and spins.  See screen shot.  I have tried on intel under 10.15.6 and M1 under 12.0.2. Not seeing any thing in system.log or ~/Library/Logs.  Is there another place I should look for logs?
![Screen Shot 2022-02-11 at 9 32 11 AM](https://user-images.githubusercontent.com/5263924/153610224-9730d6ea-c033-41e7-a3ed-2a841e720613.png)

**Comment by everetteallen** [comment]
Same result. Spins and never deletes

**Comment by BIG-RAT** [comment]
Should be resolved in v2.2.0

**Comment by everetteallen** [comment]
Confirmed I was able to delete 140 scripts in about 1 minute on cloud hosted JSS using version 2.2.0(1).  Thanks
