### ISSUE TITLE
Feature request: selective delete

### ISSUE THREAD

**Issue by smashism** [BIG-RAT/Prune#17]
Hi! Is it possible to selectively delete packages/etc. that come up after a check of the server? Sometimes legacy packages are helpful to keep in the DP, even if we're not using them in a policy at the moment. It'd be nice to be able to select results individually to delete.

(If there's a way to do that now, would be happy to hear it. I couldn't figure that out.)

**Comment by BIG-RAT** [comment]
You can remove the packages you want to keep (option click) then only remove what's left.  Workable?
