### ISSUE TITLE
Required permissions documented

### ISSUE THREAD

**Issue by staze** [BIG-RAT/Prune#18]
Curious if we could get it documented as to what permissions are actually required by Prune. Would rather not just make a "EVERYTHING" account.

Thanks!

**Comment by BIG-RAT** [comment]
Have to confess this hasn't popped to far up my to-do list.  If you're not familiar the following has a detailed listing of permissions needed to perform various actions through the API.   
[API Privilege Requirements](https://developer.jamf.com/jamf-pro/docs/classic-api-minimum-required-privileges-and-endpoint-mapping)
The trick will be identifying things that need the update permission.  For example deleting a script may cause an update to a policy.
