### ISSUE TITLE
Removed Item 0 of ### hangs

### ISSUE THREAD

**Issue by jared-a-young** [BIG-RAT/Prune#19]
The status wheel hangs at Removed Item 0 of ###. 
I am on v2.2.2 and authenticated as a full admin user. 
I am only trying to remove packages and no other options selected. 
Left it running for 30 minutes with same results. 
It seems to time out and ask for my username and password after a set amount of time.

**Comment by jared-a-young** [comment]
Ok after rescanning once the "timeout" happens I do have less packages that are unused. Seems like it is deleting them. Could you add a proper status bar that might be showing what is being deleted like a live log of what is happening? This would visually help to know what is going on or if it is hanging. Thanks.

**Comment by BIG-RAT** [comment]
Re-working authentication process after finding some issues.  Also adding a determinate progress bar, circle actually.

**Comment by BIG-RAT** [comment]
Just posted v2.2.3 which deals with some authentication issues.  Added a deterministic wheel to indicate delete progress.  As time permits let me know if things have improved.
