### ISSUE TITLE
Scanning Computer Groups comes back with nothing v2.2.2

### ISSUE THREAD

**Issue by tkimpton** [BIG-RAT/Prune#20]
We have lots of computer groups smart and static  i know are not being used for scoping. I log in click scan and nothing comes back

**Comment by BIG-RAT** [comment]
Works OK for other items; script, policies, packages...?  Does it at least show it's scanning for unused groups?

**Comment by tkimpton** [comment]
today its behaving very odd. It scans the computer group then keeps coming back with verify username and password dialog, eventually crashes and prompts me to reopen it. It is scanning other things no problem.

**Comment by BIG-RAT** [comment]
Thanks for the info.  Just posted v2.2.3 which deals with some authentication issues related to limited access servers.  As time permits let me know if things improve.

**Comment by tkimpton** [comment]
thanks very much this resolves the issue :)
