### ISSUE TITLE
Add a read only mode

### ISSUE THREAD

**Issue by Coros** [BIG-RAT/Prune#25]
I would like a read only mode option added to the app.  I haven't tried to delete anything yet, but I'm fearful of that button with so many objects in the output.  An option at the login prompt would be ideal.

**Comment by BIG-RAT** [comment]
A toggle switch after login is something I can think about.  At login just use an Auditor account.

**Comment by Coros** [comment]
Good idea about the auditor account.  I can use that build my reports etc.  Thanks!
