### ISSUE TITLE
Feature Request - List policies that are still scoped but disabled

### ISSUE THREAD

**Issue by drtaru** [BIG-RAT/Prune#27]
We are in the process of cleaning up our Jamf Pro server and have about 40 policies that were never unscoped, they were simply disabled.
It would be super handy for the policy scan to also list disabled policies that may still have a scope (under a separate heading).

**Comment by drtaru** [comment]
This still doesn't quite do what I want it to.
I would like it to list EVERY disabled policy regardless of if it is scoped still or not. 
For example I have an old policy to install Zoom that is scoped to all computers, but it has been disabled.
Since the scope is still set to "All Computers" Prune does not show it as it only lists "Unused Policies"

**Comment by BIG-RAT** [comment]
Thanks for the quick test.  My intent was to list such policies, clearly missed.  See if v2.3.1 provides the needed results.
