### ISSUE TITLE
Computer AEs

### ISSUE THREAD

**Issue by Shamus78** [BIG-RAT/Prune#29]
I hope i'm just missing something. when I remove the "kept items"  I then select delete and it indicates that i'm about to remove 0 objects when I have 15 items listed. I then select OK and I get a ring.

**Comment by Shamus78** [comment]
[Shamus78](https://github.com/Shamus78) commented [38 seconds ago](https://github.com/BIG-RAT/Prune/issues/29#issue-1454195422)
I hope i'm just missing something. when I remove the "kept items" I then select delete and it indicates that i'm about to remove 0 objects when I have 15 items listed. I then select OK and I get a ring.

**Comment by Shamus78** [comment]
Thank you! trying it again today I see its now seeing all the items selected but I'm getting error HTTP Status Code: 502 - 404 - 400 error for each item selected - completed with the following msg. Removal process complete. Note, 15 items were not deleted. checking my master account just to make sure I full permissions.  could this be something else?

**Comment by Shamus78** [comment]
just checked master account, has everything enabled tried it once more same results.

**Comment by Shamus78** [comment]
Thank you for looking into this BR, this is starting to look like a environmental issue, when I attempted to delete a single id via api I was given errors indicating that even though the Ea was disabled it would linked to a group and or profile. Once these where severed I was then able to delete the AE. I'll need to then back track and run this for groups and profiles and clean these out first.

**Comment by Shamus78** [comment]
Fri Nov 18 12:01:37 [remove_Action] failed to removed category computerextensionattributes with id: 64
Fri Nov 18 12:01:37 [Xml.DELETE] existing endpoints URL: https://Musicbox.jamfcloud.com/JSSResource/computerextensionattributes/id/64
Fri Nov 18 12:02:07 [Xml.DELETE] error HTTP Status Code: 502


##### manually run to determine error 
~ % curl -X DELETE "https://Musicbox.jamfcloud.com/JSSResource/computerextensionattributes/id/64" -H "accept: application/xml" -H "Authorization: Bearer cruncky"
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Bad Request</p>
<p>The following items are dependent on this Computer Extension Attribute and need to be updated: Smart Computer Group:Has Adobe Flash and needs to be uninstalled, Smart Computer Group:Has Adobe Flash and needs to be uninstalled copy </p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>

**Comment by BIG-RAT** [comment]
That helps.  Looks like EAs that are being used for smart group criteria were not being picked up.  v2.3.3 should have that resolved.
