### ISSUE TITLE
Enhancement Request: Ability to export to .csv

### ISSUE THREAD

**Issue by TaylorArmstrongB1** [BIG-RAT/Prune#38]
Would LOVE the ability to export to .csv - much easier for reporting purposes.  I'm planning out a cleanup effort, and management wants details of everything that we're going to purge.  I can certainly get it from the .json export, but a .csv export would save a lot of time.

**Comment by BIG-RAT** [comment]
You're in luck

- Option-click Export to export all items to a single CSV in your downloads folder.

**Comment by TaylorArmstrongB1** [comment]
Just FWIW, Option-click stopped working after a few days.  Option-click now just gives me a .json file.  Not the end of the world, but for change-management exporting the csv, circulating it among the team for review, and then *IMPORTING* the .csv (with any changes/deletions from the team) was an ideal workflow on our end.
