### ISSUE TITLE
Quotes in Policy Names causing JSON parsing issues

### ISSUE THREAD

**Issue by jshirle2** [BIG-RAT/Prune#39]
We had some policies that had quotes in the name which were causing issues. We exported the list of policies generated and then worked removed any policies we wanted to keep from the list. Upon importing the revised list back into Prune I was receiving a File Import Error and realized it was because of the policies with quotes in the name. 

I suspect that the JSON is not escaping the quotes properly which would cause issues.

**Comment by BIG-RAT** [comment]
I believe you suspicion is correct - thanks.  Version 3.1.0 should have the issue resolved.
