### ISSUE TITLE
Request to swap click/key function...

### ISSUE THREAD

**Issue by everetteallen** [BIG-RAT/Prune#4]
It is just too easy to remove an item from the list with a single click.  It would be great if Option Click would remove the item and double click  would take you to the jamf web page.  Would also be nice if copy and paste from any part of the list worked (ie single click selects for copy).

**Comment by BIG-RAT** [comment]
I like the idea - thanks.  Should be working in now (v1.0.5), except for the copy/paste.  I'll keep that one in mind though.

**Comment by everetteallen** [comment]
Tested and confirmed.  Thanks!
