### ISSUE TITLE
check username and password

### ISSUE THREAD

**Issue by mrmte** [BIG-RAT/Prune#41]
After a computer group scan it gets about half way through and says check username and password. We have a lot of smart groups i need to cleanup. could this be the bearer token expired and thats why it keeps popping up. When the prompt appears the only solution is to force quit the app and try again.

**Comment by mrmte** [comment]
ri Oct 06 12:47:03 [Json.getRecord] get existing endpoints URL: https://XXX.jamfcloud.com/JSSResource/policies/id/753
Fri Oct 06 12:47:04 [Json.getRecord] error during GET, HTTP Status Code: 401

**Comment by BIG-RAT** [comment]
Token expiring sounds like a likely cause.  Give v3.1.1 a try and let me know how things look as time permits.

**Comment by mrmte** [comment]
still getting same with 3.1.1

**Comment by BIG-RAT** [comment]
Added a little extra logging and found a function not running as intended.  Updated, give the following a whirl
[Prune v3.1.2-b1](https://github.com/BIG-RAT/Prune/releases/download/v3.1.2-b1/Prune_v3.1.2-b1.zip)
Should see information about the token getting renewed:
```
20231016_183049 [recursiveLookup] 2833 of 3752	 lookup: name staticGroup - 3527 - id 15343
20231016_183049 [getToken] source tokenAgeInSeconds: 1800.397
20231016_183049 [getToken] Attempting to retrieve token from Optional(https://<my>.jamfcloud.com/api/v1/auth/token)
20231016_183051 [getToken] new token created for https://<my>.jamfcloud.com
```

**Comment by mrmte** [comment]
great it works now. I got the pop up once and then it renewed and continued to finish as expected
