### ISSUE TITLE
Packages in Patch Management are listed as unused

### ISSUE THREAD

**Issue by randomName0815** [BIG-RAT/Prune#42]
the patch policies are skipped according to the log and therefore many packages are listed although they are in use there. 
It is probably due to the recent changes in the Jamf API, luckily we noticed it quickly.

Is there a patch planned or already in development?

Btw. thanks a lot for this great tool !

**Comment by BIG-RAT** [comment]
Thanks for the heads up.  Fear this one is on me as it looks like v3.0.2 scans patch policies.  
Now to track it down...

**Comment by BIG-RAT** [comment]
Give v3.1.1 a try and let me know how things look as time permits.

**Comment by randomName0815** [comment]
Hi, I just tested the 3.1.1 and it works at least partially. 
I guess only one patch policy is scanned and the version is filtered out (or is it now based on the definitions again?).
Example: For VLC Player version 3.0.18 is still shown as unused package, which is still active in a second patch policy.
![Bildschirmfoto 2023-10-16 um 09 28 39](https://github.com/BIG-RAT/Prune/assets/109347634/c4f24a34-c2b4-46f9-9421-dd2ac64d8f66)

**Comment by BIG-RAT** [comment]
Thanks for the info - time to do more digging.

**Comment by BIG-RAT** [comment]
Give [v3.1.2-b2](https://github.com/BIG-RAT/Prune/releases/download/v3.1.2-b2/Prune_v3.1.2-b2.zip) a run.  Should pick up all the packages within a patch policy.

**Comment by randomName0815** [comment]
Hi, looks good, with the new beta I no longer see anything unexpected, thank you
