### ISSUE TITLE
Packages are deleted but report as failed...

### ISSUE THREAD

**Issue by everetteallen** [BIG-RAT/Prune#43]
With Jamf Pro 11.1.3 and Prune 3.1.2-b2 Build: 20231022-1B0 that packages are successfully deleted but the log (attached) shows the delete fails and a warning dialog is given at the end of the delete run to the same effect.  However using the web GUI and the api the packages are not there (at least have no database entry).  
This instance is premium hosted and not using JCDS 2.0.
Any ideas.
[20240125_085807_prune.log](https://github.com/BIG-RAT/Prune/files/14053325/20240125_085807_prune.log)

**Comment by BIG-RAT** [comment]
Nice catch.  It's making an unnecessary call to the JCDS2 to delete a package which is taken care of automatically when you remove the record from Jamf Pro.
Error can be ignored.

**Comment by BIG-RAT** [comment]
v3.2.0 should resolve the issue.
