### ISSUE TITLE
Not able to make remove work...

### ISSUE THREAD

**Issue by everetteallen** [BIG-RAT/Prune#5]
After JNUC 2020 I tried to use Prune 1.1.0(1) to remove a single package on my JSS and got the progress spinner for 90 minutes before I stopped it (quit).  The package was not removed from the JCDS in my Jamf Cloud.  Is there a log I can get that might tell why?

**Comment by BIG-RAT** [comment]
?Best bet is to launch it from Terminal:

/Applications/Prune.app/Contents/MacOS/Prune


Provided the application is in the Applications folder of course.  Haven't gotten around to add logging yet.



________________________________

**Comment by BIG-RAT** [comment]
For version 1.2.0 I've moved much of the Terminal output to a log file: ```~/Library/Containers/com.jamf.pse.prune/Data/Library/Logs/Prune.log```

**Comment by BIG-RAT** [comment]
Still an issue?  Any logs to pass along?  Note, it can take a few/several minutes to reflect the changes in the UI on the Jamf Serer.
