### ISSUE TITLE
Documentation: Read Me does not say how "unused" is determined

### ISSUE THREAD

**Issue by everetteallen** [BIG-RAT/Prune#7]
The ReadMe does not say how "unused" is determined.  Clearly a package not assigned to a policy is covered and one of the fixed issues says that Patch Policies are looked at.  But are PreStages tested for package use, or configurations.  Basically it would be great to get a statement of what is actually looked at to determine "unused".  Thanks!

**Comment by BIG-RAT** [comment]
Added to readme, thanks for pointing out the missing info.
